development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: tamashii-clockin_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: tamashii-clockin_production
