default: &default
  mailer:
    url:
      host: <%= ENV['MAILER_HOST'] %>
  tamashii:
    mode: token
    token: <%= ENV['TAMASHII_TOKEN'] %>
  flowdock:
    token: <%= ENV['FLOWDOCK_TOKEN'] %>
    channel: <%= ENV['FLOWDOCK_CHANNEL'] %>


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
